services:
  backend:
    image: amruthkumartj/dd-mean-backend:latest
    container_name: dd-backend
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
      - MONGODB_URI=mongodb://host.docker.internal:27017/dd_db
    depends_on:
      - nginx-proxy

  frontend:
    image: amruthkumartj/dd-mean-frontend:latest
    container_name: dd-frontend
    restart: always
    command: npx ng serve --host 0.0.0.0 --port 4200 --disable-host-check

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend